export const PAGE_ROUTES = {
  DIGITAL_MARKETING_360: "/360-digital-marketing",
  ABOUT: "/about",
  ANDROID_DEVELOPMENT: "/andorid-development",
  APP_DEVELOPMENT: "/app-development",
  CONTACT: "/contact",
  CONTENT_MARKETING: "/content-marketing",
  DIGITAL_MARKETING: "/digital-marketing",
  HOME: "/",
  HYBRID_APP_DEVELOPMENT: "/hybrid-app-development",
  INFLUENCER_MARKETING: "/influencer-marketing",
  IOS_APP_DEVELOPMENT: "/ios-app-development",
  MOBILE_APP_DEVELOPMENT: "/mobile-app-development",
  PERFORMANCE_MARKETING: "/peroformance-marketing",
  PPC_MARKETING: "/ppc-marketing",
  SEO: "/seo",
  SERVICES: "/services",
  SOCIAL_MEDIA_MARKETING: "/social-media-marketing",
  WEB_DEVELOPMENT: "/webdevelopment",
  BLOGS: "/blogs",
  UI_UX_DESIGN: "/ui-ux-design",
};
