export const APP_ROUTES = {
  HOME: '/',
  ABOUT: '/about',
  CONTACT: '/contact',
  SERVICES: '/services',
  WEB_DEVELOPMENT: '/web-development',
  MOBILE_APP_DEVELOPMENT: '/mobile-app-development',
  IOS_APP_DEVELOPMENT: '/ios-app-development',
  ANDROID_APP_DEVELOPMENT: '/android-app-development',
  HYBRID_APP_DEVELOPMENT: '/hybrid-app-development',
  API_DEVELOPMENT: '/api-development',
  SOFTWARE_DEVELOPMENT: '/software-development',
  SALESFORCE_DEVELOPMENT: '/salesforce-development',
  ECOMMERCE_WEBSITE_DEVELOPMENT: '/ecommerce-website-development',
  DIGITAL_MARKETING: '/digital-marketing',
  DIGITAL_STRATEGY: '/digital-strategy',
  SEO_SERVICES: '/seo-services',
  SMM_SERVICES: '/smm-services',
  PPC_MARKETING: '/ppc-marketing',
  CONTENT_MARKETING: '/content-marketing',
  PERFORMANCE_MARKETING: '/performance-marketing',
  INFLUENCER_MARKETING: '/influencer-marketing',
  ASO_SERVICES: '/aso-services',
  UI_UX_DESIGN: '/ui-ux-design',
  VIDEO_EDITING: '/video-editing',
  CLOUD_SERVICES: '/cloud-services',
  HRMS_SOFTWARE_DEVELOPMENT: '/hrms-software-development',
  HOTEL_MANAGEMENT_SOFTWARE: '/hotel-management-software',
  SCHOOL_MANAGEMENT_SOFTWARE: '/school-management-software',
  ONLINE_RECRUITMENT_SOFTWARE: '/online-recruitment-software',
  BLOG: '/blog',
  LANDING_PAGE: '/landing-page',
  PRIVACY_POLICY: '/privacy-policy',
  TERMS_OF_SERVICE: '/terms-of-service',
  THANK_YOU: '/thank-you'
} as const;

export type AppRoute = typeof APP_ROUTES[keyof typeof APP_ROUTES]; 